### ISSUE TITLE
CA Template Request - <DNSCrypt>

### ISSUE THREAD

**Issue by itskamel** [selfhosters/unRAID-CA-templates#160]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/DNSCrypt/dnscrypt-server-docker

#### Post any additional information about the project that you know is important 
dns encryption

**Comment by Roxedus** [comment]
Sadly I cant say this is template I want to maintain, because:
* It requires pregenereted certs, this is not something the template can really do anything with, the user has to generate them, or use a cert from other means, IE the letsencrypt container.
* Most, if not all settings are set as run-arguments rather than environment variables, which is not something that can be templated easily.

The only thing that can be templated is the port and repository field, the rest is up to the user.
