### ISSUE TITLE
CA Template Request - Mafl (creator already made the XML, just needs to be added to CA)

### ISSUE THREAD

**Issue by Sonny-Crockett** [selfhosters/unRAID-CA-templates#491]
### Application does not already exist

- [X] I have verified that the requested application template does not already exist in Community Apps, or that the existing Community App template is out of date and no longer maintained.

### Application is actively supported

- [X] I have verified that the requested application is actively maintained.

### Link to Docker Hub or GitHub Container Registry

https://raw.githubusercontent.com/hywax/mafl/main/templates/unraid.xml

### Link to source code

https://github.com/hywax/mafl

**Comment by nwithan8** [comment]
Seems easy enough, but since the lead developer has already made the XML template (only two hours before this ticket was opened), let's give it a few days in case they're gearing up to supply it to CA themselves. Wouldn't want to step on their toes and/or make a template in this repo that is just going to be instantly deprecated in favor of the "official" one.

**Comment by Sonny-Crockett** [comment]
[https://github.com/hywax/mafl/issues/102#issuecomment-2122603079](url)

Totally understand, no worries. My only thinking was(I think haha) that you need an unRAID box to actually upload to CA, and they said that they do not have access to one. 

I am in no rush so I am good either way!
